### ISSUE TITLE
tlmgr itself needs to be updated

### ISSUE THREAD

**Issue by rugk** [fermiumlabs/latex-docker#11]
When I try to install `texliveonfly` it requires an update:

```sh
$ tlmgr install texliveonfly
===============================================================================
tlmgr itself needs to be updated.
Please do this via either
  tlmgr update --self
or by getting the latest updater for Unix-ish systems:
  http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
and/or Windows systems:
  http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.exe
Then continue with other updates as usual.
===============================================================================
tlmgr: Terminating; please see warning above!
tlmgr: package repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet (verified)
````

**Comment by ddavidebor** [comment]
Hello, sorry for the long wait, I was travelling abroad without the laptop.
Here is a cute rock for you, meanwhile the CI builds and tests the pull request #12 


![IMG_4284-min](https://user-images.githubusercontent.com/9055742/68087990-26538e80-fe5b-11e9-9446-72851da2e998.jpg)
![IMG_4269-min](https://user-images.githubusercontent.com/9055742/68088002-379c9b00-fe5b-11e9-895c-4156282037c1.jpg)

**Comment by ddavidebor** [comment]
Should be up in 1 hours or so
