### ISSUE TITLE
Update to TexLive 2020

### ISSUE THREAD

**Issue by rugk** [fermiumlabs/latex-docker#20]
This still uses the TexLive 2019 version. An upgrade to 2020 would be nice.

**Comment by ddavidebor** [comment]
Hi @rugk Indeed it would

I’ve been very busy as I moved to another country, if you could help with a PR it would be appreciated

**Comment by ddavidebor** [comment]
Fixed in #22

**Comment by rugk** [comment]
Thanks! :tada:
